[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.minimal"

[deploy]
startCommand = "apache2-foreground"
healthcheckPath = "/"
healthcheckTimeout = 300

[env]
NIXPACKS_IGNORE_FILE_CONFLICTS = "true"