[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.railway"

[deploy]
startCommand = "/usr/local/bin/entrypoint.sh apache2-foreground"
healthcheckPath = "/"
healthcheckTimeout = 300

[env]
NIXPACKS_IGNORE_FILE_CONFLICTS = "true"