[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.minimal-php"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300

[env]
APP_ENV = "production"
APP_DEBUG = "false"
LOG_CHANNEL = "stderr"
LOG_LEVEL = "info"